package3/objects/Merchant__mdt.object
<CustomObject>
    <description>Represents a Merchant used in the Adyen interface. The Merchant record contains all connection params</description>
    <label>Merchant</label>
    <pluralLabel>Merchants</pluralLabel>
    <fields>
        <fullName>API_Key__c</fullName>
        <description>Used as the X-API-KEY header in Adyen requests</description>
        <inlineHelpText>Used as the X-API-KEY header in Adyen requests</inlineHelpText>
        <label>API Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Authorise_Endpoint__c</fullName>
        <defaultValue>&quot;https://checkout-test.adyen.com/v49/&quot;</defaultValue>
        <description>Endpoint to which the Adyen Authorise service is mounted</description>
        <inlineHelpText>Endpoint to which the Adyen Authorise service is mounted</inlineHelpText>
        <label>Authorise Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Capture_Endpoint__c</fullName>
        <description>Endpoint of the Adyen capture service</description>
        <inlineHelpText>Endpoint of the Adyen capture service</inlineHelpText>
        <label>Capture Endpoint</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Name of the Merchant, passed to the Adyen API as such</description>
        <inlineHelpText>Name of the Merchant, passed to the Adyen API as such</inlineHelpText>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

package3/classes/TestSetupController.cls
@IsTest
private class TestSetupController {

    static testMethod void testInit() {
        Test.startTest();
        SetupController setupController = new SetupController();
        List<Merchant__mdt> merchants = setupController.settings;
        System.assert(merchants.size()>0,'Expected a minimum of 1 Merchant record');
        System.assertEquals(false, setupController.needsRefresh,'Expected needsRefresh false');
        Test.stopTest();

    }

    static testMethod void testNewRow() {
        Test.startTest();
        SetupController setupController = new SetupController();
        setupController.newRow();
        Test.stopTest();
        System.assert(setupController.editingRow<>null,'Expected empty Merchant row');
        System.assertEquals('',setupController.editingRow.MasterLabel,'Expected empty Merchant MasterLabel');
    }

    @isTest
    static void testCancel() {
        Test.startTest();
        SetupController setupController = new SetupController();
        setupController.cancel();
        System.assertEquals(null, setupController.editingRow, 'Expected no row in edit mode anymore after cancel');
        Test.stopTest();
    }
    @isTest
    static void testEditRow() {
        Test.startTest();
        SetupController setupController = new SetupController();
        setupController.editId = 'ApexTest';
        System.assertEquals(Page.EditSetupRecord.getUrl(),setupController.editRow().getUrl(),'Expected to be in edit page');
        System.assertEquals('ApexTest',setupController.editingRow.QualifiedApiName,'Expected ApexTest in edit mode');

        Test.stopTest();
    }
    @isTest
    static void testSaveRow() {
        Test.startTest();
        SetupController setupController = new SetupController();
        setupController.newRow();
        setupController.editingRow.MasterLabel = 'X X';
        setupController.editingRow.Name__c = 'X X';
        setupController.editingRow.Authorise_Endpoint__c = 'http://test.org';
        setupController.editingRow.Capture_Endpoint__c = 'http://test.org';
        setupController.editingRow.API_Key__c = 'TOKEN';
        setupController.saveRow();
        System.assertEquals(true, setupController.needsRefresh,'Expected needsRefresh true');
        System.assertEquals('X_X',setupController.editingRow.QualifiedApiName,'Expected underscored spaces');
        System.assertEquals('APEX',setupController.jobId,'Expected "APEX" jobid');
        setupController.jobReady();
        System.assertEquals(null,setupController.jobId,'Expected null jobid');
        Test.stopTest();
    }


}