package3/objects/Merchant__mdt.object
<CustomObject>
    <description>Represents a Merchant used in the Adyen interface. The Merchant record contains all connection params</description>
    <label>Merchant</label>
    <pluralLabel>Merchants</pluralLabel>
    <fields>
        <fullName>API_Key__c</fullName>
        <description>Used as the X-API-KEY header in Adyen requests</description>
        <inlineHelpText>Used as the X-API-KEY header in Adyen requests</inlineHelpText>
        <label>API Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Authorise_Endpoint__c</fullName>
        <defaultValue>&quot;https://checkout-test.adyen.com/v49/&quot;</defaultValue>
        <description>Endpoint to which the Adyen Authorise service is mounted</description>
        <inlineHelpText>Endpoint to which the Adyen Authorise service is mounted</inlineHelpText>
        <label>Authorise Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Capture_Endpoint__c</fullName>
        <description>Endpoint of the Adyen capture service</description>
        <inlineHelpText>Endpoint of the Adyen capture service</inlineHelpText>
        <label>Capture Endpoint</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Merchant__mdt/fields/Disable_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Disable_Endpoint__c</fullName>
    <defaultValue></defaultValue>
    <description>Endpoint to which the Adyen Disable service is mounted</description>
    <inlineHelpText>Endpoint to which the Adyen Disable service is mounted</inlineHelpText>
    <label>Disable Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Merchant__mdt/fields/Payment_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Payment_Endpoint__c</fullName>
    <defaultValue>&quot;https://checkout-test.adyen.com/v66/&quot;</defaultValue>
    <description>Endpoint to which the Adyen Payment service is mounted</description>
    <inlineHelpText>Endpoint to which the Adyen Payment service is mounted</inlineHelpText>
    <label>Payment Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/AdyenClient.cls
//
// Contains the callouts to the Adyen API
public class AdyenClient {
    public static AuthoriseResponse authorisePayment(Merchant__mdt merchantRecord, OASPaymentRequest request) {
        ccrz.ccLog.log(LoggingLevel.DEBUG,'DebugBas', request);
        AuthoriseResponse output = new AuthoriseResponse();
        try {
            Http httpClient = new Http();
            HttpRequest httpReq = new HttpRequest();
            httpReq.setEndpoint(merchantRecord.Payment_Endpoint__c);
            httpReq.setMethod('POST');
            httpReq.setHeader('X-API-KEY', merchantRecord.API_Key__c);
            httpReq.setHeader('Content-Type', 'application/json');
            String jsonString = JSON.serialize(request, true);
            jsonString = Util.stripX(jsonString);
            System.Debug('## Raw request '+jsonString);
            httpReq.setBody(jsonString);
            HttpResponse httpResp = httpClient.send(httpReq);
            System.Debug('## Raw response '+httpResp.getBody());
            if(httpResp.getStatusCode() == 200) {
                output = (AuthoriseResponse) JSON.deserialize(Util.replaceDots(httpResp.getBody()), AuthoriseResponse.class);
                output.success = true;
            } else {
                output.errorDetail =  (Error) JSON.deserialize(httpResp.getBody(), Error.class);
                if(output.errorDetail.status==null) {
                    output.errorDetail.status = httpResp.getStatusCode();
                }
                output.success = false;
            }
        }
        catch(Exception e) {
            output.errorDetail = new Error();
            output.errorDetail.message = 'Adyen callout failed: '+e.getMessage();
            output.success = false;
        }
        return output;
    }
//    public static CaptureResponse capturePayment(Merchant__mdt merchantRecord, CaptureRequest request) {
//        CaptureResponse output = new CaptureResponse();
//        try {
//            Http httpClient = new Http();
//            HttpRequest httpReq = new HttpRequest();
//            httpReq.setEndpoint(merchantRecord.Capture_Endpoint__c);
//            httpReq.setMethod('POST');
//            httpReq.setHeader('X-API-KEY',merchantRecord.API_Key__c);
//            httpReq.setHeader('Content-Type','application/json');
//            String jsonString = JSON.serialize(request);
//            jsonString = Util.stripX(jsonString);
//            httpReq.setBody(jsonString);
//            HttpResponse httpResp = httpClient.send(httpReq);
//            //System.Debug('## Raw response '+httpResp.getBody());
//            if(httpResp.getStatusCode() == 200) {
//                output = (CaptureResponse) JSON.deserialize(httpResp.getBody(), CaptureResponse.class);
//                output.success = true;
//            } else {
//                output.errorDetail =  (Error) JSON.deserialize(httpResp.getBody(), Error.class);
//                output.success = false;
//                if(output.errorDetail.status==null) {
//                    output.errorDetail.status = httpResp.getStatusCode();
//                }
//            }
//        }
//        catch(Exception e) {
//            output.errorDetail = new Error();
//            output.errorDetail.message = 'Adyen capture failed: '+e.getMessage();
//            output.success = false;
//        }
//
//        return output;
//    }
//    public static DisableResponse disablePaymentMethod(Merchant__mdt merchantRecord, DisableRequest request) {
//        DisableResponse output = new DisableResponse();
//        try {
//            Http httpClient = new Http();
//            HttpRequest httpReq = new HttpRequest();
//            httpReq.setEndpoint(merchantRecord.Disable_Endpoint__c);
//            httpReq.setMethod('POST');
//            httpReq.setHeader('X-API-KEY',merchantRecord.API_Key__c);
//            httpReq.setHeader('Content-Type','application/json');
//            String jsonString = JSON.serialize(request);
//            jsonString = Util.stripX(jsonString);
//            httpReq.setBody(jsonString);
//            HttpResponse httpResp = httpClient.send(httpReq);
//            //System.Debug('## Raw response '+httpResp.getBody());
//            if(httpResp.getStatusCode() == 200) {
//                output = (DisableResponse) JSON.deserialize(httpResp.getBody(), DisableResponse.class);
//                output.success = true;
//            } else {
//                output.errorDetail =  (Error) JSON.deserialize(httpResp.getBody(), Error.class);
//                output.success = false;
//                if(output.errorDetail.status==null) {
//                    output.errorDetail.status = httpResp.getStatusCode();
//                }
//            }
//        }
//        catch(Exception e) {
//            output.errorDetail = new Error();
//            output.errorDetail.message = 'Adyen disable failed: '+e.getMessage();
//            output.success = false;
//        }
//
//        return output;
//    }
//    public static AuthoriseResponse updatePaymentMethod(Merchant__mdt merchantRecord, AuthoriseRequest request) {
//        AuthoriseResponse output = new AuthoriseResponse();
//        try {
//            Http httpClient = new Http();
//            HttpRequest httpReq = new HttpRequest();
//            httpReq.setEndpoint(merchantRecord.Authorise_Endpoint__c);
//            httpReq.setMethod('POST');
//            httpReq.setHeader('X-API-KEY', merchantRecord.API_Key__c);
//            httpReq.setHeader('Content-Type', 'application/json');
//            String jsonString = JSON.serialize(request, true);
//            jsonString = Util.stripX(jsonString);
//            //System.Debug('## Raw request '+jsonString);
//            httpReq.setBody(jsonString);
//            HttpResponse httpResp = httpClient.send(httpReq);
//            //System.Debug('## Raw response '+httpResp.getBody());
//            if(httpResp.getStatusCode() == 200) {
//                output = (AuthoriseResponse) JSON.deserialize(Util.replaceDots(httpResp.getBody()), AuthoriseResponse.class);
//                output.success = true;
//            } else {
//                output.errorDetail =  (Error) JSON.deserialize(httpResp.getBody(), Error.class);
//                if(output.errorDetail.status==null) {
//                    output.errorDetail.status = httpResp.getStatusCode();
//                }
//                output.success = false;
//            }
//        }
//        catch(Exception e) {
//            output.errorDetail = new Error();
//            output.errorDetail.message = 'Adyen callout failed: '+e.getMessage();
//            output.success = false;
//        }
//        return output;
//    }
}