package3/objects/Merchant__mdt.object
<CustomObject>
    <description>Represents a Merchant used in the Adyen interface. The Merchant record contains all connection params</description>
    <label>Merchant</label>
    <pluralLabel>Merchants</pluralLabel>
    <fields>
        <fullName>API_Key__c</fullName>
        <description>Used as the X-API-KEY header in Adyen requests</description>
        <inlineHelpText>Used as the X-API-KEY header in Adyen requests</inlineHelpText>
        <label>API Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Authorise_Endpoint__c</fullName>
        <defaultValue>&quot;https://checkout-test.adyen.com/v49/&quot;</defaultValue>
        <description>Endpoint to which the Adyen Authorise service is mounted</description>
        <inlineHelpText>Endpoint to which the Adyen Authorise service is mounted</inlineHelpText>
        <label>Authorise Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Capture_Endpoint__c</fullName>
        <description>Endpoint of the Adyen capture service</description>
        <inlineHelpText>Endpoint of the Adyen capture service</inlineHelpText>
        <label>Capture Endpoint</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Merchant__mdt/fields/Disable_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Disable_Endpoint__c</fullName>
    <defaultValue></defaultValue>
    <description>Endpoint to which the Adyen Disable service is mounted</description>
    <inlineHelpText>Endpoint to which the Adyen Disable service is mounted</inlineHelpText>
    <label>Disable Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Merchant__mdt/fields/Merchant_Account__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Account__c</fullName>
    <description>Name of the Merchant, passed to the Adyen API as such</description>
    <inlineHelpText>Name of the Merchant, passed to the Adyen API as such</inlineHelpText>
    <label>Merchant Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Merchant__mdt/fields/Payment_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Payment_Endpoint__c</fullName>
    <defaultValue>&quot;https://checkout-test.adyen.com/v66/&quot;</defaultValue>
    <description>Endpoint to which the Adyen Payment service is mounted</description>
    <inlineHelpText>Endpoint to which the Adyen Payment service is mounted</inlineHelpText>
    <label>Payment Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Merchant__mdt/fields/PaymentMethods_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethods_Endpoint__c</fullName>
    <defaultValue>&quot;https://checkout-test.adyen.com/v65/&quot;</defaultValue>
    <description>Endpoint to retrieve paymentMethods from Adyen</description>
    <inlineHelpText>Endpoint to retrieve paymentMethods from Adyen</inlineHelpText>
    <label>PaymentMethods Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Merchant__mdt/fields/Payments_Details_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Payments_Details_Endpoint__c</fullName>
    <defaultValue>&quot;https://checkout-test.adyen.com/v65/&quot;</defaultValue>
    <description>Payments Details endpoint</description>
    <inlineHelpText>Endpoint to which the Adyen Payment service is mounted</inlineHelpText>
    <label>Payments Details Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/Util.cls
//
// Utility methods
public inherited sharing class Util {

    public static Merchant__mdt getConfigByName(String configName) {
        Merchant__mdt[] configs = [
                SELECT API_Key__c, Capture_Endpoint__c, Authorise_Endpoint__c, Disable_Endpoint__c, Payment_Endpoint__c, PaymentMethods_Endpoint__c, Payments_Details_Endpoint__c, Merchant_Account__c, QualifiedApiName
                FROM Merchant__mdt
                WHERE DeveloperName = :configName
                LIMIT 1
        ];
        if (configs <> null && configs.size() == 1) {
            return configs[0];
        } else {
            return null;
        }
    }

    // Delete the suffix from Reserved Keywords
    public static String makeAdyenCompatible(String input) {
        String output = input;
        Map<String, String> mapKeyToReplace = new Map<String, String>();
        mapKeyToReplace.put('currency_x', 'currency');
        mapKeyToReplace.put('number_x', 'number');
        mapKeyToReplace.put('group_x', 'group');
        for (String key : mapKeyToReplace.keySet()) {
            output = output.replace(key, mapKeyToReplace.get(key));
        }

        return output;
    }

    //Add suffix to avoid Reserved Keywords
    public static String makeSalesforceCompatible(String input) {
        String output = input;
        Map<String, String> mapKeyToReplace = new Map<String, String>();
        mapKeyToReplace.put('recurring.recurringDetailReference', 'recurring_recurringDetailReference');
        mapKeyToReplace.put('currency', 'currency_x');
        mapKeyToReplace.put('number', 'number_x');
        mapKeyToReplace.put('group', 'group_x');
        for (String key : mapKeyToReplace.keySet()) {
            output = output.replace(key, mapKeyToReplace.get(key));
        }

        return output;
    }

    public static Map<String, Object> getCCConfig(String configModule, String storeName, Boolean safe, Boolean cache) {
        Map<String, Object> fetchMap = new Map<String, Object>();
        fetchMap.put(ccrz.ccApi.API_VERSION, ccrz.ccAPI.CURRENT_VERSION);
        fetchMap.put(ccrz.ccAPIConfig.CONFIG_MODULE, configModule);
        fetchMap.put(ccrz.ccAPIConfig.STORE_NAME, storeName);
        fetchMap.put(ccrz.ccAPIConfig.EXTERNALLY_SAFE, safe);
        fetchMap.put(ccrz.ccAPIConfig.USE_CACHE, cache);

        return (ccrz.ccAPIConfig.fetch(fetchMap));
    }

    public static Map<String, Object> getLabels(Set<String> labelNames) {
        Map<String, Object> inputData = new Map<String, Object>();
        inputData.put(ccrz.ccApi.API_VERSION, ccrz.ccAPI.CURRENT_VERSION);
        inputData.put(ccrz.ccApiI18N.PAGE_LABEL_NAMES, labelNames);

        return ccrz.ccApiI18N.fetchPageLabels(inputData);
    }

    public static Set<String> getFieldList(String objectName) {
        Map<String, Schema.SObjectType> allObj = Schema.getGlobalDescribe();
        Set<String> setFields = new Set<String>();
        if (allObj.containsKey(objectName)) {
            Schema.SObjectType sot = allObj.get(objectName);
            for (Schema.SObjectField s : sot.getDescribe().fields.getMap().values()) {
                if (s.getDescribe().getName() != 'CloneSourceId') {
                    setFields.add(s.getDescribe().getName());
                }
            }
        }
        return setFields;
    }

    public static String allFieldsCommaSeparated(Set<String> fields) {
        String output = '';
        for (String fieldName : fields) {
            if (fieldName.toLowerCase() == 'id') {
                continue; // Adding Id at the end; saves the comma hassle
            }
            output += fieldName + ', ';
        }
        output += 'Id';
        return output;
    }

    public static String getNamespacePrefix(String className) {
        String namespacePrefix;
        Type t = Type.forName(className);
        String[] classNameParts = String.valueOf(t).split('\\.', 2);
        namespacePrefix = classNameParts.size() == 2 ? classNameParts[0] : 'c';
        return namespacePrefix;
    }
}