package3/objects/Merchant__mdt.object
<CustomObject>
    <description>Represents a Merchant used in the Adyen interface. The Merchant record contains all connection params</description>
    <label>Merchant</label>
    <pluralLabel>Merchants</pluralLabel>
    <fields>
        <fullName>Name__c</fullName>
        <description>Name of the Merchant, passed to the Adyen API as such</description>
        <inlineHelpText>Name of the Merchant, passed to the Adyen API as such</inlineHelpText>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/AdyenPaymentMethodsRequest.cls
public with sharing class AdyenPaymentMethodsRequest {
     public static PaymentMethodsRequest createPaymentMethodsRequest(ccrz__E_Cart__c cart, Merchant__mdt merchant){
            PaymentMethodsRequest paymentMethodsRequest = new PaymentMethodsRequest();
            paymentMethodsRequest.merchantAccount = merchant.Name__c;
            paymentMethodsRequest.amount = AdyenUtil.getAdyenAmount(cart);
            paymentMethodsRequest.shopperReference = cart.ccrz__Account__c;
            paymentMethodsRequest.allowedPaymentMethods = new List<String> {'card', 'ideal'};
            paymentMethodsRequest.countryCode = 'US';
            return paymentMethodsRequest;
     }
}