package3/objects/Merchant__mdt.object
<CustomObject>
    <description>Represents a Merchant used in the Adyen interface. The Merchant record contains all connection params</description>
    <label>Merchant</label>
    <pluralLabel>Merchants</pluralLabel>
    <fields>
        <fullName>API_Key__c</fullName>
        <description>Used as the X-API-KEY header in Adyen requests</description>
        <inlineHelpText>Used as the X-API-KEY header in Adyen requests</inlineHelpText>
        <label>API Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Authorise_Endpoint__c</fullName>
        <defaultValue>&quot;https://checkout-test.adyen.com/v49/&quot;</defaultValue>
        <description>Endpoint to which the Adyen Authorise service is mounted</description>
        <inlineHelpText>Endpoint to which the Adyen Authorise service is mounted</inlineHelpText>
        <label>Authorise Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Capture_Endpoint__c</fullName>
        <description>Endpoint of the Adyen capture service</description>
        <inlineHelpText>Endpoint of the Adyen capture service</inlineHelpText>
        <label>Capture Endpoint</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Name of the Merchant, passed to the Adyen API as such</description>
        <inlineHelpText>Name of the Merchant, passed to the Adyen API as such</inlineHelpText>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <description>Optional local reference passed to Adyen when Authorising Payments.</description>
        <inlineHelpText>Optional local reference passed to Adyen when Authorising Payments.</inlineHelpText>
        <label>Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

package2/classes/Util.cls
//
// Utility methods
public class Util {
    //
    // Strip off the _x's needed to avoid protected keywords
    public static String stripX(String input) {
        String output = input;
        if(output <> null) {
            output = output.replace('_x','');
        }
        return output;
    }
    public static Merchant__mdt getConfigByName(String configName) {
        Merchant__mdt[] configs = [SELECT API_Key__c, Capture_Endpoint__c, Authorise_Endpoint__c, Name__c, Reference__c, QualifiedApiName FROM Merchant__mdt WHERE QualifiedApiName=:configName LIMIT 1];
        if(configs <> null && configs.size()==1) {
            return configs[0];
        } else {
            return null;
        }
    }
}