package2/objects/ccrz__E_TransactionPayment__c.object
<CustomObject>
</CustomObject>

package3/objects/Merchant__mdt.object
<CustomObject>
    <description>Represents a Merchant used in the Adyen interface. The Merchant record contains all connection params</description>
    <label>Merchant</label>
    <pluralLabel>Merchants</pluralLabel>
    <fields>
        <fullName>API_Key__c</fullName>
        <description>Used as the X-API-KEY header in Adyen requests</description>
        <inlineHelpText>Used as the X-API-KEY header in Adyen requests</inlineHelpText>
        <label>API Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Capture_Endpoint__c</fullName>
        <description>Endpoint of the Adyen capture service</description>
        <inlineHelpText>Endpoint of the Adyen capture service</inlineHelpText>
        <label>Capture Endpoint</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Merchant__mdt/fields/Merchant_Account__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Account__c</fullName>
    <description>Name of the Merchant, passed to the Adyen API as such</description>
    <inlineHelpText>Name of the Merchant, passed to the Adyen API as such</inlineHelpText>
    <label>Merchant Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AdyenCaptureRequest.cls
public with sharing class AdyenCaptureRequest {
    public static CaptureRequest createCaptureRequest(ccrz__E_TransactionPayment__c tp, Merchant__mdt merchant) {
        CaptureRequest captureRequest = new CaptureRequest();
        captureRequest.merchantAccount = merchant.Merchant_Account__c;
        captureRequest.originalReference = tp.ccrz__TransactionCode__c;
        captureRequest.modificationAmount = AdyenUtil.getAdyenAmount(tp.ccrz__CurrencyISOCode__c, tp.ccrz__Amount__c);
        captureRequest.reference = tp.Id;
        return captureRequest;
    }

    public static CaptureResponse sendCaptureRequest(Merchant__mdt merchant, CaptureRequest request) {
        CaptureResponse captureResponse = new CaptureResponse();
        AdyenClient client = new AdyenClient(merchant.API_Key__c, merchant.Capture_Endpoint__c);
        String jsonString = JSON.serialize(request, true);
        jsonString = Util.makeAdyenCompatible(jsonString);
        HttpResponse httpResponse = client.request(client.config, jsonString);

        if (AdyenUtil.isHttpResponseOK(httpResponse.getStatusCode())) {
            captureResponse = (CaptureResponse) JSON.deserialize(Util.makeSalesforceCompatible(httpResponse.getBody()), CaptureResponse.class);
        } else {
            System.Debug('## Response code ' + httpResponse.getStatusCode() + 'from /capture call');
            System.Debug('## /capture raw response: ' + httpResponse.getBody());
        }

        return captureResponse;
    }

}