package2/objects/ccrz__E_TransactionPayment__c.object
<CustomObject>
    <fields>
        <fullName>Capture_Payment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to Capture a Payment from an Auth transaction</description>
        <inlineHelpText>Used to Capture a Payment from an Auth transaction</inlineHelpText>
        <label>Capture Payment</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/default/classes/TransactionPaymentHandler.cls
public with sharing class TransactionPaymentHandler {
    public static void capturePayments(List<ccrz__E_TransactionPayment__c> listNew, Map<Id,ccrz__E_TransactionPayment__c> mapOld){
        Set<Id> setIds = new Set<Id>();

        for(ccrz__E_TransactionPayment__c tp : listNew){
            if(tp.Capture_Payment__c && !mapOld.get(tp.Id).Capture_Payment__c){
                setIds.add(tp.Id);
            }
        }

        if(setIds.size()>0){
            //number of callouts per transaction is 100
            Database.executeBatch(new BatchCapturePayment(setIds), 10);
        }
    }
}