force-app/main/default/objects/ccrz__E_Cart__c/fields/AdyenPaymentData__c.field-meta.xml
<CustomField>
        <fullName>AdyenPaymentData__c</fullName>
        <label>AdyenPaymentData</label>
        <length>131072</length>
        <type>LongTextArea</type>
</CustomField>

package3/objects/Merchant__mdt.object
<CustomObject>
    <description>Represents a Merchant used in the Adyen interface. The Merchant record contains all connection params</description>
    <label>Merchant</label>
    <pluralLabel>Merchants</pluralLabel>
    <fields>
        <fullName>API_Key__c</fullName>
        <description>Used as the X-API-KEY header in Adyen requests</description>
        <inlineHelpText>Used as the X-API-KEY header in Adyen requests</inlineHelpText>
        <label>API Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Merchant__mdt/fields/Payments_Details_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Payments_Details_Endpoint__c</fullName>
    <defaultValue>&quot;https://checkout-test.adyen.com/v65/&quot;</defaultValue>
    <description>Payments Details endpoint</description>
    <inlineHelpText>Endpoint to which the Adyen Payment service is mounted</inlineHelpText>
    <label>Payments Details Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/AdyenPaymentsDetails.cls
public with sharing class AdyenPaymentsDetails {
    public static PaymentsResponse requestFromStateData(string stateData){
        PaymentsDetailsRequest paymentsDetailsRequest = (PaymentsDetailsRequest) JSON.deserialize(stateData, PaymentsDetailsRequest.class);
        return callPaymentsDetails(paymentsDetailsRequest);
    }

    public static PaymentsResponse requestAfterRedirect(Map<String, String> details, String cartEncryptedId){
        ccrz__E_Cart__c cart = AdyenUtil.getCartByEncryptedId(cartEncryptedId);
        PaymentsDetailsRequest paymentsDetailsRequest = new PaymentsDetailsRequest();
        paymentsDetailsRequest.details = details;
        //Get saved payment data from cart
        paymentsDetailsRequest.paymentData = cart.AdyenPaymentData__c;
        return callPaymentsDetails(paymentsDetailsRequest);
    }

    public static PaymentsResponse callPaymentsDetails(PaymentsDetailsRequest request){
        PaymentsResponse paymentsDetailsResponse = new PaymentsResponse();
        Merchant__mdt merchant = Util.getConfigByName('AdyenMerchantConfig');

        AdyenClient client = new AdyenClient(merchant.API_Key__c, merchant.Payments_Details_Endpoint__c);
        String jsonString = JSON.serialize(request, true);
        jsonString = Util.makeAdyenCompatible(jsonString);
        HttpResponse httpResponse = client.request(client.config, jsonString);
        if (AdyenUtil.isHttpResponseOK(httpResponse.getStatusCode())) {
            paymentsDetailsResponse = (PaymentsResponse) JSON.deserialize(Util.makeSalesforceCompatible(httpResponse.getBody()), PaymentsResponse.class);
        } else {
            System.Debug('## Response code ' + httpResponse.getStatusCode() + 'from /payments/details call');
            System.Debug('## /payments/details raw response: ' + httpResponse.getBody());
        }

        return paymentsDetailsResponse;
    }
}